server:
  port: 1111
  
spring:
  application:
    name: API-GATEWAY
   
#greet & Feign as an alias names we can give whatever we want  
zuul:
  prefix: /ms
  routes:
    greet:    
      path: /api1/**
      service-id: STOCK-PRICE-API
    Feign:
      path: /api2/**
      service-id: STOCK-CALC-API
   
   
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka